[package]
name    = "arrow-client"
version = "0.6.1"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]
license = "Apache-2.0"
readme  = "README.md"
build   = "build.rs"

[features]
discovery = []

[dependencies]
libc            = "0.2"
mio             = "=0.5.1"
regex           = "0.1"
time            = "0.1"
rustc-serialize = "0.3"

bytes        = "0.4"
futures      = "0.1"
tokio-core   = "0.1"
tokio-io     = "0.1"
tokio-timer  = "0.1"
serde        = "1.0"
serde_json   = "1.0"
serde_derive = "1.0"

[dependencies.uuid]
version  = "0.5"
features = ["use_std", "v4", "serde"]

[dependencies.openssl]
version  = "0.8.3"
features = ["tlsv1_2"]

[build-dependencies]
gcc = "0.3"

[profile.dev]
opt-level = 0
debug     = true
panic     = "unwind"

[profile.release]
opt-level = 3
debug     = false
panic     = "abort"
