[package]
name    = "arrow-client"
version = "0.4.2"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]
license = "Apache-2.0"
readme  = "README.md"
build   = "build.rs"

[features]
discovery = []

[dependencies]
libc            = "0.2"
regex           = "0.1"
uuid            = "0.1"
time            = "0.1"
rustc-serialize = "0.3"

# TODO: use a new version of mio (based on libc 0.2.x) as soon as it is 
# available
[dependencies.mio]
git = "https://github.com/carllerche/mio.git"
rev = "abd5dd356d9aa7670285f10baf237a27103155dd"

[dependencies.openssl]
version  = "0.7.3"
features = ["tlsv1_2"]

[build-dependencies]
gcc = "0.3"

[profile.dev]
opt-level = 0
debug     = true

[profile.release]
opt-level = 3
debug     = false
