[package]
name    = "arrow-client"
version = "0.8.0"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]
license = "Apache-2.0"
readme  = "README.md"
build   = "build.rs"

[features]
discovery = []
threads = []

[dependencies]
bytes        = "0.4"
farmhash     = "1.1"
futures      = "0.1"
json         = "0.11"
lazy_static  = "1.3"
libc         = "0.2"
num_cpus     = "1.10"
openssl      = "0.10"
time         = "0.1"
tokio        = "0.1"

[dependencies.uuid]
version  = "0.7"
features = ["v4"]

[build-dependencies]
cc = "1.0"

[profile.dev]
opt-level = 0
debug     = true

[profile.release]
opt-level     = 3
debug         = false
panic         = "abort"
lto           = true
codegen-units = 1
incremental   = false
