[package]
name    = "arrow-client"
version = "0.7.1"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]
license = "Apache-2.0"
readme  = "README.md"
build   = "build.rs"

[features]
discovery = []

[dependencies]
bytes        = "0.4.5"
farmhash     = "1.1.5"
futures      = "0.1.16"
json         = "0.11.9"
lazy_static  = "1.0.0"
libc         = "0.2.31"
openssl      = "0.9.23"
time         = "0.1.38"
tokio        = "0.1.6"
tokio-io     = "0.1.3"

[dependencies.uuid]
version  = "0.6.1"
features = ["v4"]

[build-dependencies]
cc = "1.0.2"

[profile.dev]
opt-level = 0
debug     = true
panic     = "abort"

[profile.release]
opt-level     = 3
debug         = false
panic         = "abort"
lto           = true
codegen-units = 1
incremental   = false
